// Sons em formato base64 - sons sintéticos leves para feedback instantâneo
// Estes são sons gerados sinteticamente e são muito pequenos (<5KB cada)

// Som de click suave
export const CLICK_SOUND =
  'data:audio/wav;base64,UklGRhwAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YfgAAAAAAAD//wAAAP7/AgACAP//AQABAP//AQAAAP//AgAAAP//AQAAAP//AgACAP7/AgABAPz/BAD//wAABQD6/wYA/P8CABEA7/8YANn/LQCq/3gAdv8EAUv/gwEk/+wBH/8tAin/UwIz/1YCNv84Ai//8gEm/58BGf9WARf/FQEY/+MAGP+5ABH/kwAH/2wA/P5LAO/+LADX/hAAtf72AJn+5QB6/tQAXv7MAD/+xQAf/sAABf7BAO39wwDd/cYA0v3KAM/9zwDT/dMA2f3VAOb91wD1/dcAA/7WAA3+0wAX/s8AIP7KACH+xQAe/sEAGv69ABL+uQAM/rYACf6zAAn+sQAI/q8ADf6uABL+rQAZ/q4AIP6wACj+swAu/rUANf64ADn+ugA6/r0AOv7AADX+wgAy/sQALf7FAC3+xwAs/scAMP7IADX+xwA9/sYARv7FAFL+xABf/sIAcf7BAIn+wACm/r8Ay/6+APj+vgAu/70AbP+9ALb/vQAIAL0AXwC9ALkAvQAXAb0AdwG+ANcBvgA2Ar4AkwK+AO0CvgBEA74AlQO+AOMD'

// Som de sucesso (tarefa concluída)
export const SUCCESS_SOUND =
  'data:audio/wav;base64,UklGRkQBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSABAAAAAQAEAAcACgAMAA4AEAARABIAEwAUABQAFQAUABQAFAAUABQAEwASABEAEAAOAAwACgAIAAYAAwABAP//BAASACMAPQBXAHMAgQCMAJkApACvALgAwADHAMwAzwDRANIA0ADNAN0A7AD3AAABCgESARgBHQEgASIBIQEfARoBFAEMAfkA6ADXAMQA'

// Som de XP ganho (tom ascendente)
export const XP_SOUND =
  'data:audio/wav;base64,UklGRloBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YTYBAAADAAYACgAOABIAFgAaAB4AIgAmACkALAAuADEAMgAyADIAMQAwAC4AKwAnACMAHwAaABQADgAHAAAA/P8AAAUA'

// Som de moedas (tilintante)
export const COINS_SOUND =
  'data:audio/wav;base64,UklGRmoBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YUYBAAABAAIABAAHAAoADQAQABQAGAAbAB8AJAAoACwAMAA1ADkAPAA/AEAAPwA9ADkANAAtACQAGwARAAgA//8FABIA'

// Som de level up (fanfarra curta)
export const LEVEL_UP_SOUND =
  'data:audio/wav;base64,UklGRoQBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YWABAAABAAIAAwAFAAYABwAJAAoACwAMAAcAEQAfACoANgA/AEQASABIAEYARABDAM0AQAD//w=='

// Som de conquista (badge)
export const ACHIEVEMENT_SOUND =
  'data:audio/wav;base64,UklGRp4BAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YXoBAAABAAIABAAHAAsADwAUABkAHwAlACoAMAA1ADoAPQBAAEIARQBJAEsATABNAE0ATgBNAEsASgBJAEUAQgA+ADoANwAzAC4AKgAlAB8A'

// Som de notificação
export const NOTIFICATION_SOUND =
  'data:audio/wav;base64,UklGRngBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YVQBAAACAAMABQAHAAUAJQA3AFYAbQCBAJIAoQCsALUAvQDEAMcAyQDKAMsAygDKAMkAxwDFAMIAvgC6ALQArgCnAKAAl'

// Som de erro
export const ERROR_SOUND =
  'data:audio/wav;base64,UklGRkQBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSABAACAgH9+f4CBgoGCgoKCgYGBgIB/f35+fn5+f4CAgYGCg4ODg4ODgoKCgYGAgIB/f35+fn5/f4CAgYGCgoODg4ODg4KCgoGBgYCAf39/fn5+fn9/f4CAgYGCgoKDg4ODg4KCgoGBgYCAf39/f35+fn5/f3+AgIGBgoKCg4ODg4ODgoKCgYGBgIB/f39+fn5+f39/gICBgYKCgoODg4ODg4KCgoGBgYCAf39/'

// Som de pop
export const POP_SOUND =
  'data:audio/wav;base64,UklGRjQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YRAAAAD//wEABAD9/wAA/v8AAA=='

// Som de toggle
export const TOGGLE_SOUND =
  'data:audio/wav;base64,UklGRkQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAAAAACAAQABgAHAAcABgAFAAMAAgD//wAA//8AAP//AAD//w=='

// Som de recompensa
export const REWARD_SOUND =
  'data:audio/wav;base64,UklGRqQBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YYABAAABAAIABAAHAAoADgASABYAGgAfACMAJwArAC8AMwA2ADkAPAA+AEAAQQBCAEIAQgBBAEAAQAA/AD0APAA6ADgANQAyAC8A'

// Som de meditação (tom suave)
export const MEDITATION_SOUND =
  'data:audio/wav;base64,UklGRuABAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YbwBAAABAAEAAgACAAMAAwADAAQABAAEAAUABQAFAAUABgAGAAYABgAGAAcABwAHAAcABwAHAAcABwAHAAcABwAH'

// Som de meditação completa
export const MEDITATION_COMPLETE_SOUND =
  'data:audio/wav;base64,UklGRgACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YdwBAAABAAIAAwAFAAYACAAKAAwADgAQABIAFQAXABkAGwAdAB8AIAAiACMAJAAlACUAJgAmACYAJgAmACUA'

// Som de diário
export const JOURNAL_SOUND =
  'data:audio/wav;base64,UklGRmQBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YUABAAABAAIABAAFAAcACQALAA0ADwARABMAFQAXABgAGgAbABwAHAAcABwAGwAaABgAFgATABAADAAI'

// Som de humor
export const MOOD_SOUND =
  'data:audio/wav;base64,UklGRlQBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YTABAAABAAIABAAGAAgACgAMAA4AEAASABQAFgAYABkAGwAcABwAHQAdABwAHAAbABoAGAAWABQAEgAPAAw='

// Som de streak
export const STREAK_SOUND =
  'data:audio/wav;base64,UklGRnQBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YVABAAABAAIABAAGAAgACwANABAAEgAVABcAGQAbAB0AHwAhACIAIwAkACQAJQAlACQAJAAjACIAIAAeABwAGgAX'

// Som de navegação
export const NAVIGATION_SOUND =
  'data:audio/wav;base64,UklGRjQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YRAAAAD//wAAAgD//wAA//8AAAEA'

// Som de delete
export const DELETE_SOUND =
  'data:audio/wav;base64,UklGRkwBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSgBAAACAP//BQAIAAUA//8GAP3/BAD9////AgD8//3/AwD8//v/BQD8//n/BwD8//b/CQD8//P/CwD8//D/'

// Som de swoosh
export const SWOOSH_SOUND =
  'data:audio/wav;base64,UklGRoQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YWAAAAD//wAAAgADAAQABAAFAAUABQAEAAQAAwACAAEAAAABAAIAAwADAAQABAADAAMAAgABAAAA//8AAAEA'

// Mapa de sons base64
export const BASE64_SOUNDS = {
  click: CLICK_SOUND,
  success: SUCCESS_SOUND,
  xp: XP_SOUND,
  coins: COINS_SOUND,
  levelUp: LEVEL_UP_SOUND,
  achievement: ACHIEVEMENT_SOUND,
  notification: NOTIFICATION_SOUND,
  error: ERROR_SOUND,
  pop: POP_SOUND,
  toggle: TOGGLE_SOUND,
  reward: REWARD_SOUND,
  meditation: MEDITATION_SOUND,
  meditationComplete: MEDITATION_COMPLETE_SOUND,
  journal: JOURNAL_SOUND,
  mood: MOOD_SOUND,
  streak: STREAK_SOUND,
  navigation: NAVIGATION_SOUND,
  delete: DELETE_SOUND,
  swoosh: SWOOSH_SOUND,
} as const
