/**
 * Analyzes a CBT thought record using Gemini via API route.
 */
export const analyzeThought = async (emotion: string, thought: string): Promise<string> => {
  try {
    const response = await fetch('/api/analyze-thought', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ emotion, thought }),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.error || 'Failed to analyze thought')
    }

    const data = await response.json()
    return data.analysis || 'Não foi possível gerar uma análise neste momento.'
  } catch (error) {
    console.error('Error calling analyze-thought API:', error)
    return 'Desculpe, não consegui analisar seu pensamento agora. Por favor, tente novamente mais tarde.'
  }
}

/**
 * Therapeutic Plan type generated by AI
 */
export type TherapeuticPlan = {
  objectives: string[]
  interventions: Array<{
    technique: string
    description: string
    targetBelief?: string
  }>
  suggestedActivities: string[]
  estimatedDuration: string
  observations: string
  generatedAt: string
}

type SituationData = {
  situation: string
  automaticThought: string
  meaningOfAT: string
  emotion: string
  behavior: string
}

export type CognitiveConceptualizationInput = {
  patientName?: string
  childhoodData?: string
  coreBelief?: string
  conditionalAssumptions?: string
  compensatoryStrategies?: string
  situations?: {
    situation1?: SituationData
    situation2?: SituationData
    situation3?: SituationData
  }
  notes?: string
}

/**
 * Generates a therapeutic plan based on cognitive conceptualization using AI.
 */
export const generateTherapeuticPlan = async (
  data: CognitiveConceptualizationInput
): Promise<TherapeuticPlan> => {
  try {
    const response = await fetch('/api/generate-therapeutic-plan', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.error || 'Failed to generate therapeutic plan')
    }

    return await response.json()
  } catch (error) {
    console.error('Error calling generate-therapeutic-plan API:', error)
    throw new Error(
      'Não foi possível gerar o plano terapêutico. Por favor, tente novamente mais tarde.'
    )
  }
}

/**
 * Suggests a reward cost based on its title and category using AI.
 */
export type RewardSuggestion = {
  suggestedCost: number
  reasoning: string
  valueLevel: 'baixo' | 'médio' | 'alto' | 'premium'
}

export const suggestRewardCost = async (
  title: string,
  category?: string,
  patientLevel?: number,
  patientPoints?: number
): Promise<RewardSuggestion> => {
  try {
    const response = await fetch('/api/suggest-reward-cost', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ title, category, patientLevel, patientPoints }),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.error || 'Failed to suggest reward cost')
    }

    const data = await response.json()
    return {
      suggestedCost: data.suggestedCost || 50,
      reasoning: data.reasoning || 'Sugestão baseada na categoria da recompensa.',
      valueLevel: data.valueLevel || 'médio',
    }
  } catch (error) {
    console.error('Error calling suggest-reward-cost API:', error)
    return {
      suggestedCost: 50,
      reasoning: 'Não foi possível gerar uma sugestão. Por favor, defina o valor manualmente.',
      valueLevel: 'médio',
    }
  }
}
